---
name: Release service

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  releaseDEV:
    name: Release DEV
    runs-on: ubuntu-latest
    steps:
      - name: Release dummy
        run: echo "release to dev ..."
  releaseSTG:
    name: Release STG
    environment: stage
    runs-on: ubuntu-latest
    steps:
      - name: Release dummy
        run: echo "release to stg ..."